### ISSUE TITLE
chess draws vignette

### ISSUE THREAD

**Issue by RobinHankin** [RobinHankin/hyper2#13]
it would be good to have a chess draws dataset, with a nice documented analysis of the 1962 World Chess Championship.  There is a whole lot of relevant code in ```inst/collusion_curacao1962.R``` and ```inst/collusion_stockholm1962.R```.

**Comment by shabbychef** [comment]
I am not sure what you mean by a 'draws dataset', but I found a db of ~2 million games from the top-5000 site. Using that data I looked at whether [Elo should be anchored based on draw probability](https://www.gilgamath.com/elo-ties.html). My scripts for sourcing the data are [here](https://github.com/shabbychef/chessdata).

**Comment by RobinHankin** [comment]
Hi there, thanks for this.  I'm analysing chess  statistically [currently I have a paper under review], and of course draws are problematic, as you note.  I thought it would be nice to add a dataset of the 1962 world championship to the hyper2 R package [which is what a 'draws dataset' meanat].  But I too am unhappy with Elo and am working on a way to improve it. 
Best wishes,  Robin

**Comment by shabbychef** [comment]
It looks like the top-5000 db is gone, but I have an old copy of the data. I pulled out all entries from the 1961-1963 Candidates Tournament, which you can find [here](https://gist.github.com/shabbychef/5280b511cd4c892040bd896f47f17d92)
hth,

**Comment by RobinHankin** [comment]
closing, work now published in JEBO
